-- ==========================================
-- DỮ LIỆU MẪU CHO BẢNG CONSUMABLE (VTTH)
-- ==========================================
INSERT INTO `consumable` (`consumable_id`, `code`, `name`, `unit`, `min_quantity`, `note`) VALUES
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000001', 'Găng tay bảo hộ (Cotton)', 'Đôi', 100, 'Dùng cho nhân viên vận hành'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000002', 'Găng tay cách điện 22kV', 'Đôi', 20, 'Dùng cho thợ điện'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000003', 'Khẩu trang chống bụi', 'Hộp', 50, 'Hộp 50 cái'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000004', 'Dầu bôi trơn công nghiệp Shell', 'Lít', 200, 'Dầu nhờn cho hộp số'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000005', 'Mỡ chịu nhiệt bôi trơn', 'Kg', 50, 'Dùng cho vòng bi'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000006', 'Giẻ lau máy (cotton)', 'Kg', 100, 'Giẻ lau thấm hút tốt'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000007', 'Băng keo cách điện Nano đen', 'Cuộn', 200, 'Cách điện hạ thế'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000008', 'Dây thít nhựa 30cm', 'Túi', 150, 'Túi 100 sợi'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000009', 'Nước cất châm ắc quy', 'Lít', 100, 'Bảo dưỡng ắc quy 110V'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000010', 'Bóng đèn huỳnh quang 1.2m', 'Bóng', 50, 'Chiếu sáng nhà máy'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000011', 'Bóng đèn LED 15W', 'Bóng', 80, 'Dùng cho văn phòng'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000012', 'Pin AA Energizer', 'Viên', 200, 'Dùng cho thiết bị đo lường'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000013', 'Pin AAA Panasonic', 'Viên', 200, 'Dùng cho điều khiển'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000014', 'Keo dán ống PVC Bình Minh', 'Tuýp', 30, 'Dán ống nước làm mát'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000015', 'Băng tan (cao su non)', 'Cuộn', 100, 'Quấn ren ống nước'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000016', 'Silicone chịu nhiệt đỏ', 'Tuýp', 20, 'Làm kín mặt bích'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000017', 'Đá cắt sắt 100mm', 'Viên', 150, 'Vật tư tiêu hao cơ khí'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000018', 'Đá mài hợp kim', 'Viên', 100, 'Dùng mài dao cụ'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000019', 'Que hàn KT-421 (2.5mm)', 'Hộp', 40, 'Que hàn hồ quang'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000020', 'Cuộn dây hàn CO2', 'Cuộn', 20, 'Dây hàn MIG'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000021', 'Mũi khoan thép HSS 5mm', 'Cái', 50, 'Khoan sắt/thép'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000022', 'Mũi khoan bê tông 8mm', 'Cái', 30, 'Khoan tường'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000023', 'Dung dịch tẩy rửa RP7', 'Chai', 100, 'Tẩy rỉ sét'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000024', 'Lưỡi cưa sắt', 'Lưỡi', 200, 'Dùng cắt tay'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000025', 'Chổi sơn 5cm', 'Cái', 50, 'Quét sơn bảo dưỡng'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000026', 'Sơn chống rỉ mạ kẽm', 'Lon', 30, 'Bảo vệ kết cấu kim loại'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000027', 'Bao tải cát 50kg', 'Bao', 100, 'Dùng chống ngập/tràn dầu'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000028', 'Dây đai thắt ống inox', 'Mét', 50, 'Đai xiết đường ống'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000029', 'Ống nhựa PVC Phi 27', 'Ống', 50, 'Ống nước dự phòng'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTH-000030', 'Ống luồn dây điện ruột gà', 'Cuộn', 20, 'Bảo vệ cáp điện');

-- ==========================================
-- DỮ LIỆU MẪU CHO BẢNG SPARE_PART (VTTT)
-- ==========================================
INSERT INTO `spare_part` (`spare_part_id`, `code`, `name`, `unit`, `min_quantity`, `note`) VALUES
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000001', 'Vòng bi SKF 6205', 'Cái', 10, 'Bi cầu rãnh sâu'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000002', 'Vòng bi đũa NJ 210', 'Cái', 5, 'Dùng cho trục bơm'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000003', 'Phớt cơ khí (Mechanical Seal) Phi 40', 'Bộ', 8, 'Phớt bơm nước làm mát'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000004', 'Dây cu-roa B50', 'Sợi', 20, 'Truyền động động cơ'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000005', 'Cánh quạt làm mát động cơ 11kW', 'Cái', 3, 'Vật liệu nhựa chịu nhiệt'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000006', 'Gioăng mặt bích DN100', 'Cái', 50, 'Vật liệu PTFE'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000007', 'Van bi inox 304 phi 34', 'Cái', 15, 'Van khóa nước làm mát'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000008', 'Van 1 chiều lò xo phi 42', 'Cái', 10, 'Ngăn chảy ngược'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000009', 'Lưới lọc thô (Strainer) Y-Type DN50', 'Cái', 5, 'Lọc rác đầu nguồn'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000010', 'Cầu chì 10A 250V', 'Quả', 100, 'Dùng cho tủ điều khiển'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000011', 'Khởi động từ (Contactor) 22A', 'Bộ', 10, 'Thiết bị đóng cắt động cơ'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000012', 'Rơ le nhiệt 12-18A', 'Cái', 15, 'Bảo vệ quá tải'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000013', 'Aptomat (MCB) 3 Pha 63A', 'Cái', 8, 'Dùng cho tủ phân phối'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000014', 'Biến tần 7.5kW', 'Bộ', 2, 'Điều khiển tốc độ động cơ'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000015', 'Cảm biến áp suất 0-10 Bar', 'Cái', 5, 'Ngõ ra 4-20mA'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000016', 'Cảm biến nhiệt độ PT100', 'Cái', 10, 'Đo nhiệt độ gối bi'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000017', 'Công tắc hành trình', 'Cái', 20, 'Limit switch cho cửa'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000018', 'Đồng hồ áp suất mặt dầu 1Mpa', 'Cái', 10, 'Hiển thị áp suất đường ống'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000019', 'Role trung gian 14 chân 24VDC', 'Cái', 30, 'Dùng trong mạch điều khiển'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000020', 'Đế Role trung gian', 'Cái', 30, 'Đế cắm role 14 chân'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000021', 'PLC Module đầu vào số', 'Bộ', 1, 'Mở rộng DI cho PLC'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000022', 'Màn hình HMI 7 inch', 'Cái', 1, 'Màn hình cảm ứng điều khiển'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000023', 'Bo mạch điều khiển kích từ', 'Bo', 2, 'Phụ tùng tủ kích từ'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000024', 'Bơm dầu nhớt trục răng', 'Cái', 2, 'Bơm dầu bôi trơn turbine'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000025', 'Bộ lọc dầu thủy lực', 'Lõi', 10, 'Lọc cặn dầu'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000026', 'Xi lanh khí nén phi 50 hành trình 100', 'Cái', 4, 'Dùng đóng mở van'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000027', 'Van điện từ (Solenoid valve) 24V', 'Cái', 10, 'Điều khiển khí nén'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000028', 'Pin lưu điện cho PLC (Lithium 3V)', 'Viên', 20, 'Backup data PLC'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000029', 'Cáp mạng công nghiệp Cat6', 'Mét', 500, 'Dây truyền thông Profinet'),
(UNHEX(REPLACE(UUID(),'-','')), 'VTTT-000030', 'Đầu cốt đồng M8', 'Túi', 20, 'Bấm cáp điện động lực');
