-- ==========================================
-- DỮ LIỆU MẪU CHO BẢNG TOOL (CÔNG CỤ DỤNG CỤ)
-- ==========================================
INSERT INTO `tool` (`tool_id`, `name`, `category`, `total_quantity`, `available_quantity`, `damaged_quantity`, `status`, `note`) VALUES
(UNHEX(REPLACE(UUID(),'-','')), 'Bộ cờ lê tròng 8-32mm', 'Dụng cụ cầm tay', 15, 15, 0, 'available', 'Thép CR-V cao cấp'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy khoan cầm tay Bosch', 'Dụng cụ điện', 5, 4, 1, 'available', 'Khoan búa 800W'),
(UNHEX(REPLACE(UUID(),'-','')), 'Đồng hồ vạn năng Fluke 17B+', 'Thiết bị đo lường', 10, 10, 0, 'available', 'Đo điện áp, dòng điện'),
(UNHEX(REPLACE(UUID(),'-','')), 'Mỏ lết răng 14 inch', 'Dụng cụ cầm tay', 20, 20, 0, 'available', 'Dùng vặn ống nước'),
(UNHEX(REPLACE(UUID(),'-','')), 'Kìm cắt cộng lực', 'Dụng cụ cầm tay', 10, 9, 1, 'available', 'Cắt sắt thép'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy mài góc Makita', 'Dụng cụ điện', 8, 8, 0, 'available', 'Đường kính đá 100mm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bộ tuốc nơ vít đóng', 'Dụng cụ cầm tay', 12, 12, 0, 'available', 'Gồm 8 chi tiết'),
(UNHEX(REPLACE(UUID(),'-','')), 'Đồng hồ đo cách điện Megger', 'Thiết bị đo lường', 3, 3, 0, 'available', 'Đo điện trở cách điện'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy cắt sắt bàn', 'Dụng cụ điện', 2, 2, 0, 'available', 'Công suất 2000W'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bộ đột lỗ kim loại', 'Dụng cụ cơ khí', 5, 5, 0, 'available', 'Dùng gia công thép tấm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Pa lăng xích kéo tay 2 Tấn', 'Thiết bị nâng hạ', 4, 4, 0, 'available', 'Chiều dài xích 5m'),
(UNHEX(REPLACE(UUID(),'-','')), 'Kích thủy lực 10 Tấn', 'Thiết bị nâng hạ', 5, 4, 1, 'available', 'Kích đội chai'),
(UNHEX(REPLACE(UUID(),'-','')), 'Ampe kìm Hioki', 'Thiết bị đo lường', 8, 8, 0, 'available', 'Đo dòng AC/DC'),
(UNHEX(REPLACE(UUID(),'-','')), 'Búa tạ 5kg', 'Dụng cụ cầm tay', 10, 10, 0, 'available', 'Cán bọc nhựa chống sốc'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy hút bụi công nghiệp', 'Thiết bị vệ sinh', 3, 2, 1, 'available', 'Dung tích 70 lít'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bơm mỡ bằng tay', 'Dụng cụ cơ khí', 15, 15, 0, 'available', 'Bơm mỡ bò bôi trơn'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bộ chìa lục giác Yato', 'Dụng cụ cầm tay', 20, 20, 0, 'available', 'Kích cỡ 1.5 - 10mm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Đồng hồ so (Dial Indicator)', 'Thiết bị đo lường', 5, 5, 0, 'available', 'Độ chia 0.01mm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Thước kẹp điện tử Mitutoyo', 'Thiết bị đo lường', 10, 10, 0, 'available', 'Khoảng đo 0-150mm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy siết bu lông bằng khí nén', 'Dụng cụ khí nén', 6, 6, 0, 'available', 'Lực siết tối đa 800Nm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bút thử điện âm tường', 'Dụng cụ điện', 30, 30, 0, 'available', 'Cảm ứng không tiếp xúc'),
(UNHEX(REPLACE(UUID(),'-','')), 'Cảo 3 chấu tháo vòng bi', 'Dụng cụ cơ khí', 8, 8, 0, 'available', 'Độ mở 150mm'),
(UNHEX(REPLACE(UUID(),'-','')), 'Kìm mỏ quạ', 'Dụng cụ cầm tay', 15, 15, 0, 'available', 'Kẹp giữ ống/phôi'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy ren ống nước', 'Dụng cụ cơ khí', 2, 2, 0, 'available', 'Ren ống 1/2 đến 2 inch'),
(UNHEX(REPLACE(UUID(),'-','')), 'Súng bắn keo silicon', 'Dụng cụ cầm tay', 20, 18, 2, 'available', 'Loại ép tay'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bộ taro ren trong và ngoài', 'Dụng cụ cơ khí', 4, 4, 0, 'available', 'Hệ ren Metric M3-M12'),
(UNHEX(REPLACE(UUID(),'-','')), 'Đèn pin chiếu sáng cầm tay', 'Thiết bị an toàn', 15, 15, 0, 'available', 'Chống cháy nổ, IP67'),
(UNHEX(REPLACE(UUID(),'-','')), 'Dây đai an toàn toàn thân', 'Bảo hộ lao động', 25, 25, 0, 'available', 'Làm việc trên cao'),
(UNHEX(REPLACE(UUID(),'-','')), 'Máy đo nhiệt độ hồng ngoại', 'Thiết bị đo lường', 4, 4, 0, 'available', 'Đo từ xa -50 đến 500 độ C'),
(UNHEX(REPLACE(UUID(),'-','')), 'Bộ cắt gió đá (Oxy-Gas)', 'Dụng cụ cơ khí', 2, 0, 2, 'damaged', 'Bị hỏng van điều áp');
